backend/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount GoodJob::Engine => 'good_job'
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  mount ActionCable.server => "/cable"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :answer_questions, only: %w[index new create] do
    collection do
      post :batch_search
      get :upload_batch_search
    end
  end
  resources :submits, only: %w[show]
  resources :rooms, only: %w[index show destroy]
  resources :messages, only: %w[index create]
  resources :chunks, only: %w[index new create]
  resources :articles, only: %w[index new create show]
  post '/predict', to: 'predict#predict'
end

backend/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :version_group, class_name: 'VersionGroup', optional: true
  has_many :images
  has_many :chunks, dependent: :destroy
  def content_for_similarity
    [name, content, version.present? ? "Версия: #{version}" : nil ].compact.join(" ")
  end
end

backend/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController


  def new;end

  def show
    @article = Article.find_by(link: params[:id])
  end
  def create
    file = params[:file_upload]
    ParseArticlesJob.perform_later(file.read.delete("\0"))
  end

  def upload_batch_search
    @submits = Submit.all.order(created_at: :desc)
  end

  def index
    @chunks = SemanticSearch.new.perform(query, :chunks)
  end

  def query
    params[:query] || ' '
  end

end

backend/app/views/articles/index.html.erb
<div class="w-full">
  <%= form_tag(articles_path, method: "get", class: "flex items-center p-4 bg-white rounded-lg") do %>
      <%= text_field_tag(:query, params[:query], class: "flex-grow p-2 text-sm text-gray-700 rounded-l-lg focus:outline-none") %>
      <button type="submit" class="p-2 bg-blue-500 text-white rounded-r-lg">
        Search
      </button>
  <% end %>
  <ol class="mt-4 space-y-2">
    <%@chunks.each_with_index do |chunk, index| %>
      <li class="p-4 bg-white rounded-lg">
        <b> <%=index +1 %>. </b>

        <%=chunk.article&.name %> <b>score</b>:
        <%=chunk.score %>
        <p><%=chunk.attributes %></p>
      </li>
    <%end %>
  </ol>
</div>

backend/app/views/articles/new.html.erb
<div class="w-full">
  <!-- Заголовок и подзаголовок -->
  <div class="text-center py-6">
    <h1 class="text-4xl font-bold text-gray-800">Загрузка новых данных</h1>
    <p class="text-xl text-gray-600 mt-2">Загрузите новые данные в формате представленном ниже, для того что бы сеть смогла ответить на все ваши вопросы</p>
  </div>
  <div class="overflow-x-auto relative shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="py-3 px-6">Page</th>
        <th scope="col" class="py-3 px-6">Content</th>
        <th scope="col" class="py-3 px-6">Title</th>
        <th scope="col" class="py-3 px-6">Category1</th>
        <th scope="col" class="py-3 px-6">Category2</th>
      </tr>

      </thead>
      <tbody>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <td class="py-4 px-6">https://rutube.ru/info/agreement/</td>
        <td class="py-4 px-6">Пункты соглашения</td>
        <td class="py-4 px-6">Генеральное пользовательское соглашение</td>
        <td class="py-4 px-6">cat 1</td>
        <td class="py-4 px-6">cat 2</td>
      </tr>
      </tbody>
    </table>
  </div>

  <!-- Форма для загрузки файла -->
  <!-- Форма для загрузки файла -->
  <form action="<%=articles_path %>" method="post" enctype="multipart/form-data" class="flex items-center p-4 bg-white rounded-lg">
    <label for="file_upload" class="block text-sm font-medium text-gray-700">Выбери файл:</label>
    <input type="file" id="file_upload" name="file_upload" class="ml-4 flex-1 block w-full rounded-md border-gray-300  focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm">
    <input type="submit" value="Загрузить" class="ml-4 px-4 py-2 border border-transparent rounded-md text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
  </form>
</div>

backend/app/views/articles/show.html.erb
<pre>
  <%= @article.content %>
</pre>